name: "init-job"
description: "Initializes a job for node.js"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: "npm"
        registry-url: "https://registry.npmjs.org"
    - name: Restore NPM
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-npm-
