on:
  release:
    types: [created]

run-name: Publish to npm

defaults:
  run:
    shell: bash

name: Release package
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish package on NPM
        run: npx lerna publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}